USB_VID = 0x239A
USB_PID = 0x80D7
USB_PRODUCT = "Blip"
USB_MANUFACTURER = "Electronut Labs"

MCU_CHIP = nrf52840

CIRCUITPY_BUILD_EXTENSIONS = hex

INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_STAGE = 1
CIRCUITPY_DIGITALINOUT_PROTOCOL = 0
CIRCUITPY_LOAD_NATIVE = 0
CIRCUITPY_MSGPACK = 0
